vector_insert_steps_OBJS = vector_insert_steps.o $(MODULES)/UsingDynamicArray/ADTVector.o 

pqueue_insert_steps_OBJS = pqueue_insert_steps.o $(MODULES)/UsingHeap/ADTPriorityQueue.o $(MODULES)/UsingDynamicArray/ADTVector.o

# Ο βασικός κορμός του Makefile
include ../common.mk

pqueue_insert_steps_ARGS = "real"
vector_insert_steps_ARGS = "real"
